load /scratch/wangwang/chisel-dummy/test_run_dir/Dummy_nonFSM_test/Dummy_nonFSM.fir
vcd load /scratch/wangwang/chisel-dummy/test_run_dir/Dummy_nonFSM_test/COMP_Dummy_FSM.vcd
show outputs
vcd run 
vcd test outputs
vcd run
vcd test outputs
vcd run
vcd test outputs
vcd run
vcd test outputs
vcd run
vcd test outputs
vcd run
vcd test outputs
vcd run
vcd test outputs
vcd run
vcd test outputs
vcd run
vcd test outputs
vcd run
vcd test outputs
vcd run
vcd test outputs
vcd run
vcd test outputs
vcd run
vcd test outputs
vcd run
vcd test outputs
vcd run
vcd test outputs
vcd run
vcd test outputs
vcd run
vcd test outputs
vcd run
vcd test outputs
vcd run
vcd test outputs
vcd run
vcd test outputs
quit